/**
 * Git Hooks Installation for Core Build
 * @requirement REQ-V2-003 - Git hooks installation
 */

import fs from 'fs-extra';
import path from 'path';

/**
 * Install git hooks
 * @requirement REQ-V2-003 - Hook installation logic
 */
export async function installGitHooks(projectRoot: string = process.cwd()): Promise<void> {
  const hooksDir = path.join(projectRoot, '.git', 'hooks');
  
  // Check if .git exists
  if (!await fs.pathExists(path.join(projectRoot, '.git'))) {
    throw new Error('Not a git repository');
  }

  // Ensure hooks directory exists
  await fs.ensureDir(hooksDir);

  // Create pre-commit hook
  const preCommitPath = path.join(hooksDir, 'pre-commit');
  const hookScript = `#!/usr/bin/env node

/**
 * AI Workflow Engine - Pre-Commit Hook
 * Auto-generated by @shadel/ai-workflow-core
 */

(async () => {
  const { preCommitHook } = await import('@shadel/ai-workflow-core/dist/hooks/pre-commit.js');
  const exitCode = await preCommitHook();
  process.exit(exitCode);
})();
`;

  // Ensure directory exists before writing
  await fs.ensureDir(path.dirname(preCommitPath));
  
  await fs.writeFile(preCommitPath, hookScript, { mode: 0o755 });

  console.log('✅ Git hooks installed!');
  console.log(`   Location: ${preCommitPath}`);
}

/**
 * Uninstall git hooks
 */
export async function uninstallGitHooks(projectRoot: string = process.cwd()): Promise<void> {
  const preCommitPath = path.join(projectRoot, '.git', 'hooks', 'pre-commit');
  
  if (await fs.pathExists(preCommitPath)) {
    await fs.remove(preCommitPath);
    console.log('✅ Git hooks uninstalled');
  } else {
    console.log('ℹ️  No hooks to uninstall');
  }
}

/**
 * Check if hooks are installed
 */
export async function areHooksInstalled(projectRoot: string = process.cwd()): Promise<boolean> {
  const preCommitPath = path.join(projectRoot, '.git', 'hooks', 'pre-commit');
  return await fs.pathExists(preCommitPath);
}

